name: build-polygeist

on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build Polygeist
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: build
        run: |
          chmod +x build-polygeist.sh
          ./build-polygeist.sh --release --force
